# Generated by Django 5.0.6 on 2025-03-17 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy_app', '0004_alter_purchase_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Medicine_supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.CharField(max_length=50)),
                ('InvoiceNo', models.CharField(max_length=50)),
                ('InvoiceDate', models.DateField()),
                ('SupplierGST', models.CharField(max_length=50)),
                ('Address', models.CharField(max_length=50)),
                ('ContactPerson', models.CharField(max_length=50)),
                ('ContactNumber', models.PositiveIntegerField()),
                ('hsn', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('batch', models.CharField(max_length=50)),
                ('expiry', models.DateField()),
                ('quantity', models.PositiveIntegerField()),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('gst', models.DecimalField(decimal_places=2, max_digits=5)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicine_suppliers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
