# Generated by Django 5.1.7 on 2025-03-25 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy_app', '0005_alter_purchase_user_medicine_supplier'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('inventory_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('hsn', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('batch', models.CharField(max_length=50)),
                ('expiry_date', models.DateField()),
                ('stock', models.PositiveIntegerField()),
                ('threshold', models.PositiveIntegerField()),
                ('mrp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('available', 'Available'), ('low_stock', 'Low Stock'), ('out_of_stock', 'Out of Stock')], default='available', max_length=20)),
            ],
            options={
                'verbose_name': 'Inventory',
                'verbose_name_plural': 'Inventories',
            },
        ),
    ]
