# Generated by Django 4.2.5 on 2025-04-03 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy_app', '0008_medicine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicine',
            name='full_composition',
        ),
    ]
